Wms custom parameters
camptocamp/inkmap pull request #50
Opened 2022-07-29 11:36 UTC by fbeqirllari

Add custom parameters like "token" to WMS

2022-08-07 20:01 UTC, jahow requested changes
Thanks for your contribution! Custom WMS params are a great feature to have. Although the implementation is correct in my opinion, I added a couple of remarks.

Would it be possible to add tests to check whether custom params are correctly taken into account if present, and if the previous behaviour still works correctly? This can be done here: https://github.com/camptocamp/inkmap/blob/9388a2e478c35cb31bd5f39759056cca14c2f445/test/unit/printer/layers.test.js#L125

2022-08-16 07:42 UTC, jahow commented on src/main/utils.js
> +  resolve(false)
Sorry it looks like you resolved this comment but I still don't think this is necessary at all

2022-08-16 07:43 UTC, jahow commented
Thanks for the adaptations! I'll fix the remaining errors and merge this if you're OK with it.

2022-08-16 12:09 UTC, jahow approved these changes
@fbeqirllari let me know if this can be merged, thanks!

2022-08-16 16:11 UTC, fbeqirllari reviewed
@jahow yes thanks for approving it

2022-08-16 16:29 UTC, merged