[GSDESCARTE-7] Handle errors in layer loading process
camptocamp/inkmap pull request #9
Opened 2020-12-02 16:52 UTC by tkohr

PR is still WIP

Following spec allows testing, when copying test data into demo directory:

```
{
  "layers": [
    {
      "type": "XYZ",
      "url": "/data/osm-tiles/{z}/{x}/{y}.png"
    }
  ],
  "size": [1024, 1024],
  "center": [12, 48],
  "dpi": 50,
  "scale": 40000000,
  "projection": "EPSG:3857"
}
```

2020-12-14 11:35 UTC, fgravin requested changes
Good approach but i think it's too complex for nothing, errors don't have to be an observable.

2020-12-14 11:35 UTC, fgravin commented on src/printer/job.js
> +            if (layerStates[i][2] && layerStates[i][2].length > 0) {
use explicit variable
```js
const canvasImage = layerStates[i][1]
const errors = layerStates[i][2]
```

2020-12-14 11:35 UTC, fgravin commented on src/printer/job.js
> +        let errors = [];
Should be typed

2020-12-14 11:35 UTC, fgravin commented on src/printer/job.js
> +          errors: errors,
```suggestion
          errors,
```

2020-12-14 11:35 UTC, fgravin commented on src/printer/layers.js
> +  let errors = [];
type

2020-12-14 11:35 UTC, fgravin commented on src/printer/layers.js
> +let errorWMS$ = new BehaviorSubject();
no need for observables here

2020-12-14 11:35 UTC, fgravin commented on src/printer/layers.js
> +      if (this.status === 0 || this.status >= 400) {
set TileState.error here

2020-12-14 11:35 UTC, fgravin commented on src/printer/layers.js
> +        errorTile$.next({ origin: tile.key, tile: tile, error: this.status });
not sure we need the size or the tile ..

2020-12-14 11:35 UTC, fgravin commented on src/printer/layers.js
> +        errorTile$.next({ origin: tile.key, tile: tile, error: this.status });
origin should be the tile url, not the key

2020-12-14 11:35 UTC, fgravin commented on src/printer/layers.js
> +
remove

2020-12-14 11:35 UTC, fgravin commented on src/printer/layers.js
> +function createErrorTile(image, tileSize, errorCode) {
move to printer/utils

2020-12-14 11:35 UTC, fgravin commented on src/printer/layers.js
> +function createErrorTile(image, tileSize, errorCode) {
type definition

2020-12-16 14:46 UTC, tkohr commented
@fgravin thanks a lot for your feedback. I have opened a much simpler PR regarding this issue here https://github.com/camptocamp/inkmap/pull/16

2020-12-23 11:08 UTC, fgravin commented
continued in https://github.com/camptocamp/inkmap/pull/16

2020-12-23 11:08 UTC, closed without merging